os: Visual Studio 2015

environment:
  matrix:
  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - cmd: set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup update
  - rustc -vV
  - cargo -vV
  - cmd: set RUST_BACKTRACE=1
  - cmd: set RUSTFLAGS=-C target-feature=+crt-static

cache:
   - '%USERPROFILE%\.cargo'

build_script:
  - cargo build %cargoflags%

test_script:
  - cargo test %cargoflags% --all
  - cargo run -p exonum-testkit --example timestamping %cargoflags%
  - cargo run -p exonum-testkit --example configuration_change %cargoflags%
