[package]
name = "exonum-encoding"
version = "0.5.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com/"
repository = "https://github.com/exonum/exonum"
documentation = "https://docs.rs/exonum-encoding"
readme = "README.md"
license = "Apache-2.0"
keywords = ["encoding", "serialization", "deserialization", "exonum"]
categories = ["encoding"]
description = "Serialization used in the Exonum project."

[badges]
travis-ci = { repository = "exonum/exonum" }

[dependencies]
byteorder = "1.1.0"
hex = "0.3.0"
bit-vec = "0.4.4"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_json = "1.0.2"

[dev-dependencies]
pretty_assertions = "0.4.0"
