[package]
name = "exonum-consensus-tests"
version = "0.13.0-rc.2"
edition = "2018"
authors = ["The Exonum Team <contact@exonum.com>"]
license = "Apache-2.0"
description = "A collection of tests of the Exonum consensus algorithm."
publish = false

[dependencies]
exonum = { version = "0.13.0-rc.2", path = "../../exonum" }
exonum-crypto = { version = "0.13.0-rc.2", path = "../../components/crypto" }
exonum-derive = { version = "0.13.0-rc.2", path = "../../components/derive" }
exonum-keys = { version = "0.13.0-rc.2", path = "../../components/keys" }
exonum-merkledb = { version = "0.13.0-rc.2", path = "../../components/merkledb" }

bincode = "1.2.1"
bit-vec = "0.6.0"
chrono = { version = "0.4.6", features = ["serde"] }
failure = "0.1.5"
futures = "0.1.25"
log = "0.4.0"
rand = "0.7"
serde = "1.0"
serde_derive = "1.0"
