on: [push]

name: Code Coverage

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install Dependencies
        run: |
          sudo add-apt-repository -y ppa:exonum/rocksdb
          sudo apt-get install build-essential libsodium-dev libsnappy-dev libssl-dev protobuf-compiler \
          libprotobuf-dev librocksdb6.8 pkg-config clang-7 lldb-7 lld-7
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests'
      - uses: actions-rs/grcov@v0.1
